apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0t7f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0t7f
    app.kubernetes.io/part-of: tkwch-fix-0075-0059-app
  name: devfile-sample-0t7f
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0t7f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0t7f
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0059-tenant/tkwch-fix-0075-0059-app/devfile-sample-0t7f@sha256:15395833a78aad76e6de3122a902df251108a0fe535c3a8e946713f45a54d056
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
